steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kubeflow-test-380515/first_app-master', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kubeflow-test-380515/first_app-master']